### ISSUE TITLE
Server Console Errors

### ISSUE THREAD

**Issue by Intemes** [EwyBoy/EwysWorkshop#3] opened 2015-10-16 17:16 UTC
Hey, first thanks for taking over work on this mod! Greatly appreciated!

I've been having this error beeing "spammed" on my servers console:

```
[19:02:06] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$ItemCraftedEvent@707aad12:
java.lang.NullPointerException
        at tconstruct.tools.TinkerToolEvents.onCrafting(TinkerToolEvents.java:39) ~[TinkerToolEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_377_TinkerToolEvents_onCrafting_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570) [FMLCommonHandler.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:108) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:91) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onProduction(UnitCrafting.java:524) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.Unit.produce(Unit.java:154) [Unit.class:?]
        at com.ewyboy.ewysworkshop.page.unit.Unit.onUpdate(Unit.java:184) [Unit.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:265) [UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.PageMain.onUpdate(PageMain.java:51) [PageMain.class:?]
        at com.ewyboy.ewysworkshop.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:317) [TileEntityTable.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

According to https://github.com/SlimeKnights/TinkersConstruct/issues/1504 this is caused by the Workshop?

Thanks!

**Comment by EwyBoy** [comment] 2015-10-19 09:13
Hello! Looks like TCon and the Workshop are fighting over some incompatible code. I will look into this. Thanks!

**Comment by Haggle1996** [comment] 2016-03-08 00:01
This is still occurring in the latest workshop.

https://github.com/Haggle1996/RevolutionPack/issues/319#issuecomment-193489962

**Comment by EwyBoy** [comment] 2016-03-08 00:31
Still have not found out how to solve this issue

**Comment by EwyBoy** [comment] 2016-06-26 02:31
Its seems to be some kind of problems with meta tools. Not sure how to fix buts on the crafting event. I have to check it out.

**Comment by EwyBoy** [comment] 2016-06-26 02:45
Okey, I found the problem, it should be fixed in the latest build here; http://minecraft.curseforge.com/projects/ewys-workshop/files/upload

**Comment by Rob5Underscores-zz** [comment] 2016-08-25 15:09
Still occurring in v1.1.2, using SkyFactory 2.5 pack.

**Comment by JorVaCoding** [comment] 2016-08-26 23:43
Can someone tell me what to do to reproduce this log?
I can't seem to figure out what the issue is.

**Comment by EwyBoy** [comment] 2016-08-27 00:06
###### Forge Version & Ewy's Workshop Versions

> Type here

###### Expected behavior

> Type here

###### Actual Behavior

> Type here

###### Link to Crashlog or Forgelog [If Applicable]

> Type here

###### Steps to reproduce [If Applicable]

> Type here

**Comment by Rob5Underscores-zz** [comment] 2016-08-27 10:49
The forge version is 1614 ([Thermos](https://github.com/CyberdyneCC/Thermos/releases)) and v1.1.2 as mentioned above. Can't say any steps to reproduce as its on a production server, lots of people playing.

**Comment by EwyBoy** [comment] 2016-08-27 19:17
We need the steps to reproduce this to be able to fix this issue.

**Comment by JorVaCoding** [comment] 2016-09-06 22:53
#14

**Closed as completed by JorVaCoding** 2016-09-06 22:53 UTC
Labels: bug, mod compat, 1.7

**Comment by EwyBoy** [comment] 2016-09-07 00:29
This issue should be fix in our next build.
